apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fabric-logger.name" . }}-{{ .Values.peer.peerName }}-network-config
data:
  network.yaml: |-
    name: Fabric
    version: "1.0"
    
    channels:
      {{- range .Values.peer.channels }}
      {{ . }}:
        peers:
          {{ $.Values.peer.peerName }}:
            eventSource: true
      {{- end }}
    
    organizations:
      org:
        mspid: {{ .Values.peer.mspName }}
        peers:
        - {{ .Values.peer.peerName }}
        adminPrivateKey:
          path: /var/hyperledger/msp/keystore/key.pem
        signedCert:
          path: /var/hyperledger/msp/signcerts/cert.pem
    
    peers:
      {{- range .Values.peers }}
      {{ $.peerName }}:
        url: {{ $.peerScheme }}://{{ $.peerAddress }}:{{ $.peerPort }}
        grpcOptions:
          ssl-target-name-override: {{ $.peerAddress }}
          grpc.keepalive_time_ms: 600000
        {{- if eq $.peerScheme "grpcs"}}
        tlsCACerts:
          path: /var/hyperledger/msp/tlscacert/tlscacert.pem
        {{- end }}
      {{- end }}
  fabriclogger.yaml: |-
    fabric:
      blockType: {{ .Values.fabric.blockType }}
      discovery: {{ .Values.fabric.discovery }}
      asLocalhost: {{ .Values.fabric.asLocalhost }}
      channels:
        {{- range .Values.channels }}
        - {{ . }}
        {{- end }}
      ccevents:
        {{- range .Values.ccevents }}
        - channelName: {{ .channelName }}
          chaincodeId: {{ .chaincodeId }}
        {{- end }}