global:
    scrape_interval: 10s

scrape_configs:
    - job_name: fabric
      honor_labels: true
      static_configs:
          - targets:
                - orderer1.example.com:7060
                - orderer2.example.com:7060
                - orderer3.example.com:7060
                - peer1.org0.example.com:7061
                - peer2.org0.example.com:7061
                - peer1.org1.example.com:7061
                - peer2.org1.example.com:7061
