name: CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: node:12-alpine
        steps:
            - uses: actions/checkout@v2
            - name: Build fabric-logger CLI
              run: |
                  yarn install --frozen-lockfile
                  yarn build
    docker-image:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: splunkdlt/dlt-connect-libs/actions/build-publish-container@actions
              with:
                  publish-type: pre-release
                  ghcr-org: splunkdlt
                  ghcr-release-name: fabric-logger
                  ghcr-prerelease-name: fabric-logger-pre
                  ghcr-user: ${{ secrets.GHCR_USER }}
                  ghcr-pat: ${{ secrets.GHCR_PAT }}
                  github-token: ${{ secrets.GITHUB_TOKEN }}
    unit-tests:
        runs-on: ubuntu-latest
        container:
            image: node:12-alpine
        steps:
            - uses: actions/checkout@v2
            - name: Run unit tests and linter
              run: |
                  yarn install --frozen-lockfile
                  yarn build
                  yarn test --verbose
              env:
                  CI: true
    check-format:
        runs-on: ubuntu-latest
        container:
            image: node:12-alpine
        steps:
            - uses: actions/checkout@v2
            - name: Check code format
              run: |
                  yarn install --frozen-lockfile
                  yarn lint
              env:
                  CI: true
    check-helm:
        runs-on: ubuntu-latest
        container:
            image: quay.io/helmpack/chart-testing:v3.1.1
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Run chart-testing (lint)
              run: |
                  mkdir -p build
                  helm lint helm-chart/fabric-logger

    package-helm:
        runs-on: ubuntu-latest
        container:
            image: quay.io/helmpack/chart-testing:v3.1.1
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Package
              run: |
                  mkdir -p build
                  helm package -d build helm-chart/fabric-logger
            - name: Archive helm package
              uses: actions/upload-artifact@v2
              with:
                  name: fabric-logger-helm
                  path: build

    trigger-release:
        runs-on: ubuntu-latest
        needs:
            - build
            - docker-image
            - unit-tests
            - check-format
            - check-helm
            - package-helm
        if: github.ref == 'refs/heads/master'
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 12
            - name: Semantic release
              run: |
                  yarn install --frozen-lockfile
                  yarn semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Upload version
              uses: actions/upload-artifact@v2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  name: version
                  path: build/VERSION
